### ISSUE TITLE
Train dataset generate

### ISSUE THREAD

**Issue by Sirius-Li** [KaiChen1998/GeoDiffusion#21]
In the trainability part, the paper say 'first filter bounding boxes smaller than 0.2% of the image area, then augment the bounding boxes by randomly flipping with 0.5 probability and shifting no more than 256 pixels.', how does this implemented? 
I found that train_pipline set random_flip with a probability of 0.5 in data config, however, this will cause image different from gt annotations in faster rcnn training. Should I first filter annotations and random filp with a probability of 0.5, and then set train_pipline.random_flip zero in data config to generate the images for faster rcnn training?

**Comment by KaiChen1998** [comment]
> first filter bounding boxes smaller than 0.2% of the image area, then augment the bounding boxes by randomly flipping with 0.5 probability and shifting no more than 256 pixels.

Yes, the augmentation above is only applied to the annotations of the training set (instead of the training images), which are then taken as inputs for `GeoDiffusion` to generate augmented images. After that, the augmented annotations and the generated images are used as augmentation sets to train the Faster R-CNN model and the real training dataset. During the training procedure of Faster R-CNN, you can set the random flip ratio as you want.

**Comment by Sirius-Li** [comment]
So 0.5 random flip in train pipeline is to argument the train of geodiffusion model?

**Comment by KaiChen1998** [comment]
If you are referring [here](https://github.com/KaiChen1998/GeoDiffusion/blob/main/configs/data/nuimage_256x256.py#L5) when you mention `train pipeline`, then yes, it is the config for training GeoDiffusion instead of training Faster R-CNN. For configs training Faster R-CNN, we refer readers to check the official repo of [MMDeterction](https://github.com/open-mmlab/mmdetection).

**Comment by Sirius-Li** [comment]
thanks a lot for your help!
Moreover, I found at most 18 layouts can be input to geodiffusion.should I filter layouts more than 18 out in the annotations in training set both in the train of geodiffusion and faster rcnn?

**Comment by KaiChen1998** [comment]
The reason why we introduce a maximum #layout here is that the max sequence length of the text encoder is 77 for Stable Diffusion (check more details [here](https://github.com/KaiChen1998/GeoDiffusion/blob/main/utils/data/nuimage.py#L73). Empirically we find using a max #layout of 18 achieves the best performance for a **trained** `GeoDiffusion` model to generate new images during inference time. Therefore, for training `GeoDiffusion`, you do not have to use 18, while to generate images for training Faster R-CNN, 18 is a recommended threshold.

**Comment by Sirius-Li** [comment]
Alright, thanks a lot for your help!
